template:
  path: shinypro_redirector.yaml
stack_name: staging-shiny-redirector
parameters:
  SubDomainName: staging
  AcmCertificateArn: arn:aws:acm:us-east-1:797640923903:certificate/5a757f47-4660-4b7f-8108-d724269a31f5
  RedirectFctName: staging-shiny-redirectfct
