template:
  path: admodeladexplorer-redirector.yaml
stack-name: staging-admodeladexplorer-redirector
stack_tags:
  Department: IT
  Project: Infrastructure
  OwnerEmail: x.schildwachter@sagebionetworks.org
parameters:
  StackType: staging
  AcmCertificateArn: arn:aws:acm:us-east-1:797640923903:certificate/103cdd6c-b7a8-4a40-a375-da1f8ee0db5c