template_path: VPCPeer.yaml
stack_name: peering-nlpsandbox
parameters:
  PeerVPC: vpc-0f809761f28e9e350
  PeerVPCOwner: 841415736403
  PeerVPCCIDR: 10.255.21.0/24
  PeerRoleName: sagebase-vpc-peering-request-AuthorizerRole-NZ421S77TZ3Y